#!/bin/bash
# script for Installer boot OS X El Capitan 

echo "==============================================="
echo "Installer  Pre-Install Script"
echo "==============================================="
echo "====================================================="




hdiutil attach /Volumes/installer_OS/BaseSystem.dmg -noverify -nobrowse -mountpoint /Volumes/installer_Base

cp -R -p /Volumes/installer_Base/ "${3}/" 

cp -R -p /Volumes/installer_OS/BaseSystem.chunklist "${3}/"

rm -R "${3}/System/Installation/Packages"

cp -R -p  /Volumes/installer_OS/Packages "${3}/System/Installation/Packages"


hdiutil detach /Volumes/installer_Base

cp -R -p /Volumes/installer_OS/BaseSystem.dmg "${3}/"

hdiutil detach /Volumes/installer_OS

Sleep 2

exit
